//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace TestForm.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AutomationWebServiceSoap", Namespace="http://ASEKS.AutomationWebService.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MarshalByRefObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OracleParameter[]))]
    public partial class AutomationWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LinkTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFAMachineTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerForm_ASSY_QueryTableToXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback Perform_ASSY_QueryTableToStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback Perform_ASSY_QueryMESStepNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback Perform_ASSY_QueryMESLotStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerForm_FA_QueryTableToXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback Perform_FA_QueryTableToStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback Perform_FA_ExecuteNonQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback Perform_STG_ExecuteNonQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback Perform_STG_QueryPPSPictureQtyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AutomationWebService() {
            this.Url = global::TestForm.Properties.Settings.Default.TestForm_WebReference_AutomationWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LinkTestCompletedEventHandler LinkTestCompleted;
        
        /// <remarks/>
        public event GetFAMachineTypeCompletedEventHandler GetFAMachineTypeCompleted;
        
        /// <remarks/>
        public event PerForm_ASSY_QueryTableToXMLCompletedEventHandler PerForm_ASSY_QueryTableToXMLCompleted;
        
        /// <remarks/>
        public event Perform_ASSY_QueryTableToStringCompletedEventHandler Perform_ASSY_QueryTableToStringCompleted;
        
        /// <remarks/>
        public event Perform_ASSY_QueryMESStepNameCompletedEventHandler Perform_ASSY_QueryMESStepNameCompleted;
        
        /// <remarks/>
        public event Perform_ASSY_QueryMESLotStateCompletedEventHandler Perform_ASSY_QueryMESLotStateCompleted;
        
        /// <remarks/>
        public event PerForm_FA_QueryTableToXMLCompletedEventHandler PerForm_FA_QueryTableToXMLCompleted;
        
        /// <remarks/>
        public event Perform_FA_QueryTableToStringCompletedEventHandler Perform_FA_QueryTableToStringCompleted;
        
        /// <remarks/>
        public event Perform_FA_ExecuteNonQueryCompletedEventHandler Perform_FA_ExecuteNonQueryCompleted;
        
        /// <remarks/>
        public event Perform_STG_ExecuteNonQueryCompletedEventHandler Perform_STG_ExecuteNonQueryCompleted;
        
        /// <remarks/>
        public event Perform_STG_QueryPPSPictureQtyCompletedEventHandler Perform_STG_QueryPPSPictureQtyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/LinkTest", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkTest() {
            object[] results = this.Invoke("LinkTest", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkTestAsync() {
            this.LinkTestAsync(null);
        }
        
        /// <remarks/>
        public void LinkTestAsync(object userState) {
            if ((this.LinkTestOperationCompleted == null)) {
                this.LinkTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkTestOperationCompleted);
            }
            this.InvokeAsync("LinkTest", new object[0], this.LinkTestOperationCompleted, userState);
        }
        
        private void OnLinkTestOperationCompleted(object arg) {
            if ((this.LinkTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkTestCompleted(this, new LinkTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/GetFAMachineType", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFAMachineType(string vMachineId) {
            object[] results = this.Invoke("GetFAMachineType", new object[] {
                        vMachineId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFAMachineTypeAsync(string vMachineId) {
            this.GetFAMachineTypeAsync(vMachineId, null);
        }
        
        /// <remarks/>
        public void GetFAMachineTypeAsync(string vMachineId, object userState) {
            if ((this.GetFAMachineTypeOperationCompleted == null)) {
                this.GetFAMachineTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFAMachineTypeOperationCompleted);
            }
            this.InvokeAsync("GetFAMachineType", new object[] {
                        vMachineId}, this.GetFAMachineTypeOperationCompleted, userState);
        }
        
        private void OnGetFAMachineTypeOperationCompleted(object arg) {
            if ((this.GetFAMachineTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFAMachineTypeCompleted(this, new GetFAMachineTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/PerForm_ASSY_QueryTableToXML", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerForm_ASSY_QueryTableToXML(string vSQL) {
            object[] results = this.Invoke("PerForm_ASSY_QueryTableToXML", new object[] {
                        vSQL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PerForm_ASSY_QueryTableToXMLAsync(string vSQL) {
            this.PerForm_ASSY_QueryTableToXMLAsync(vSQL, null);
        }
        
        /// <remarks/>
        public void PerForm_ASSY_QueryTableToXMLAsync(string vSQL, object userState) {
            if ((this.PerForm_ASSY_QueryTableToXMLOperationCompleted == null)) {
                this.PerForm_ASSY_QueryTableToXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerForm_ASSY_QueryTableToXMLOperationCompleted);
            }
            this.InvokeAsync("PerForm_ASSY_QueryTableToXML", new object[] {
                        vSQL}, this.PerForm_ASSY_QueryTableToXMLOperationCompleted, userState);
        }
        
        private void OnPerForm_ASSY_QueryTableToXMLOperationCompleted(object arg) {
            if ((this.PerForm_ASSY_QueryTableToXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerForm_ASSY_QueryTableToXMLCompleted(this, new PerForm_ASSY_QueryTableToXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/Perform_ASSY_QueryTableToString", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Perform_ASSY_QueryTableToString(string vSQL) {
            object[] results = this.Invoke("Perform_ASSY_QueryTableToString", new object[] {
                        vSQL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Perform_ASSY_QueryTableToStringAsync(string vSQL) {
            this.Perform_ASSY_QueryTableToStringAsync(vSQL, null);
        }
        
        /// <remarks/>
        public void Perform_ASSY_QueryTableToStringAsync(string vSQL, object userState) {
            if ((this.Perform_ASSY_QueryTableToStringOperationCompleted == null)) {
                this.Perform_ASSY_QueryTableToStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerform_ASSY_QueryTableToStringOperationCompleted);
            }
            this.InvokeAsync("Perform_ASSY_QueryTableToString", new object[] {
                        vSQL}, this.Perform_ASSY_QueryTableToStringOperationCompleted, userState);
        }
        
        private void OnPerform_ASSY_QueryTableToStringOperationCompleted(object arg) {
            if ((this.Perform_ASSY_QueryTableToStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Perform_ASSY_QueryTableToStringCompleted(this, new Perform_ASSY_QueryTableToStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/Perform_ASSY_QueryMESStepName", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Perform_ASSY_QueryMESStepName(string vLotId, string vStepname) {
            object[] results = this.Invoke("Perform_ASSY_QueryMESStepName", new object[] {
                        vLotId,
                        vStepname});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Perform_ASSY_QueryMESStepNameAsync(string vLotId, string vStepname) {
            this.Perform_ASSY_QueryMESStepNameAsync(vLotId, vStepname, null);
        }
        
        /// <remarks/>
        public void Perform_ASSY_QueryMESStepNameAsync(string vLotId, string vStepname, object userState) {
            if ((this.Perform_ASSY_QueryMESStepNameOperationCompleted == null)) {
                this.Perform_ASSY_QueryMESStepNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerform_ASSY_QueryMESStepNameOperationCompleted);
            }
            this.InvokeAsync("Perform_ASSY_QueryMESStepName", new object[] {
                        vLotId,
                        vStepname}, this.Perform_ASSY_QueryMESStepNameOperationCompleted, userState);
        }
        
        private void OnPerform_ASSY_QueryMESStepNameOperationCompleted(object arg) {
            if ((this.Perform_ASSY_QueryMESStepNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Perform_ASSY_QueryMESStepNameCompleted(this, new Perform_ASSY_QueryMESStepNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/Perform_ASSY_QueryMESLotState", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Perform_ASSY_QueryMESLotState(string vLotId) {
            object[] results = this.Invoke("Perform_ASSY_QueryMESLotState", new object[] {
                        vLotId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Perform_ASSY_QueryMESLotStateAsync(string vLotId) {
            this.Perform_ASSY_QueryMESLotStateAsync(vLotId, null);
        }
        
        /// <remarks/>
        public void Perform_ASSY_QueryMESLotStateAsync(string vLotId, object userState) {
            if ((this.Perform_ASSY_QueryMESLotStateOperationCompleted == null)) {
                this.Perform_ASSY_QueryMESLotStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerform_ASSY_QueryMESLotStateOperationCompleted);
            }
            this.InvokeAsync("Perform_ASSY_QueryMESLotState", new object[] {
                        vLotId}, this.Perform_ASSY_QueryMESLotStateOperationCompleted, userState);
        }
        
        private void OnPerform_ASSY_QueryMESLotStateOperationCompleted(object arg) {
            if ((this.Perform_ASSY_QueryMESLotStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Perform_ASSY_QueryMESLotStateCompleted(this, new Perform_ASSY_QueryMESLotStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/PerForm_FA_QueryTableToXML", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerForm_FA_QueryTableToXML(string vSQL) {
            object[] results = this.Invoke("PerForm_FA_QueryTableToXML", new object[] {
                        vSQL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PerForm_FA_QueryTableToXMLAsync(string vSQL) {
            this.PerForm_FA_QueryTableToXMLAsync(vSQL, null);
        }
        
        /// <remarks/>
        public void PerForm_FA_QueryTableToXMLAsync(string vSQL, object userState) {
            if ((this.PerForm_FA_QueryTableToXMLOperationCompleted == null)) {
                this.PerForm_FA_QueryTableToXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerForm_FA_QueryTableToXMLOperationCompleted);
            }
            this.InvokeAsync("PerForm_FA_QueryTableToXML", new object[] {
                        vSQL}, this.PerForm_FA_QueryTableToXMLOperationCompleted, userState);
        }
        
        private void OnPerForm_FA_QueryTableToXMLOperationCompleted(object arg) {
            if ((this.PerForm_FA_QueryTableToXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerForm_FA_QueryTableToXMLCompleted(this, new PerForm_FA_QueryTableToXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/Perform_FA_QueryTableToString", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Perform_FA_QueryTableToString(string vSQL) {
            object[] results = this.Invoke("Perform_FA_QueryTableToString", new object[] {
                        vSQL});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Perform_FA_QueryTableToStringAsync(string vSQL) {
            this.Perform_FA_QueryTableToStringAsync(vSQL, null);
        }
        
        /// <remarks/>
        public void Perform_FA_QueryTableToStringAsync(string vSQL, object userState) {
            if ((this.Perform_FA_QueryTableToStringOperationCompleted == null)) {
                this.Perform_FA_QueryTableToStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerform_FA_QueryTableToStringOperationCompleted);
            }
            this.InvokeAsync("Perform_FA_QueryTableToString", new object[] {
                        vSQL}, this.Perform_FA_QueryTableToStringOperationCompleted, userState);
        }
        
        private void OnPerform_FA_QueryTableToStringOperationCompleted(object arg) {
            if ((this.Perform_FA_QueryTableToStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Perform_FA_QueryTableToStringCompleted(this, new Perform_FA_QueryTableToStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/Perform_FA_ExecuteNonQuery", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Perform_FA_ExecuteNonQuery(string vSQL, CommandType vcommandtype, OracleParameter[] parameters) {
            object[] results = this.Invoke("Perform_FA_ExecuteNonQuery", new object[] {
                        vSQL,
                        vcommandtype,
                        parameters});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Perform_FA_ExecuteNonQueryAsync(string vSQL, CommandType vcommandtype, OracleParameter[] parameters) {
            this.Perform_FA_ExecuteNonQueryAsync(vSQL, vcommandtype, parameters, null);
        }
        
        /// <remarks/>
        public void Perform_FA_ExecuteNonQueryAsync(string vSQL, CommandType vcommandtype, OracleParameter[] parameters, object userState) {
            if ((this.Perform_FA_ExecuteNonQueryOperationCompleted == null)) {
                this.Perform_FA_ExecuteNonQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerform_FA_ExecuteNonQueryOperationCompleted);
            }
            this.InvokeAsync("Perform_FA_ExecuteNonQuery", new object[] {
                        vSQL,
                        vcommandtype,
                        parameters}, this.Perform_FA_ExecuteNonQueryOperationCompleted, userState);
        }
        
        private void OnPerform_FA_ExecuteNonQueryOperationCompleted(object arg) {
            if ((this.Perform_FA_ExecuteNonQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Perform_FA_ExecuteNonQueryCompleted(this, new Perform_FA_ExecuteNonQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/Perform_STG_ExecuteNonQuery", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Perform_STG_ExecuteNonQuery(string vSQL, CommandType vcommandtype, OracleParameter[] parameters) {
            object[] results = this.Invoke("Perform_STG_ExecuteNonQuery", new object[] {
                        vSQL,
                        vcommandtype,
                        parameters});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Perform_STG_ExecuteNonQueryAsync(string vSQL, CommandType vcommandtype, OracleParameter[] parameters) {
            this.Perform_STG_ExecuteNonQueryAsync(vSQL, vcommandtype, parameters, null);
        }
        
        /// <remarks/>
        public void Perform_STG_ExecuteNonQueryAsync(string vSQL, CommandType vcommandtype, OracleParameter[] parameters, object userState) {
            if ((this.Perform_STG_ExecuteNonQueryOperationCompleted == null)) {
                this.Perform_STG_ExecuteNonQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerform_STG_ExecuteNonQueryOperationCompleted);
            }
            this.InvokeAsync("Perform_STG_ExecuteNonQuery", new object[] {
                        vSQL,
                        vcommandtype,
                        parameters}, this.Perform_STG_ExecuteNonQueryOperationCompleted, userState);
        }
        
        private void OnPerform_STG_ExecuteNonQueryOperationCompleted(object arg) {
            if ((this.Perform_STG_ExecuteNonQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Perform_STG_ExecuteNonQueryCompleted(this, new Perform_STG_ExecuteNonQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ASEKS.AutomationWebService.org/Perform_STG_QueryPPSPictureQty", RequestNamespace="http://ASEKS.AutomationWebService.org/", ResponseNamespace="http://ASEKS.AutomationWebService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Perform_STG_QueryPPSPictureQty(string vLotid, string vStepName, string vMagazineNo) {
            object[] results = this.Invoke("Perform_STG_QueryPPSPictureQty", new object[] {
                        vLotid,
                        vStepName,
                        vMagazineNo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Perform_STG_QueryPPSPictureQtyAsync(string vLotid, string vStepName, string vMagazineNo) {
            this.Perform_STG_QueryPPSPictureQtyAsync(vLotid, vStepName, vMagazineNo, null);
        }
        
        /// <remarks/>
        public void Perform_STG_QueryPPSPictureQtyAsync(string vLotid, string vStepName, string vMagazineNo, object userState) {
            if ((this.Perform_STG_QueryPPSPictureQtyOperationCompleted == null)) {
                this.Perform_STG_QueryPPSPictureQtyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerform_STG_QueryPPSPictureQtyOperationCompleted);
            }
            this.InvokeAsync("Perform_STG_QueryPPSPictureQty", new object[] {
                        vLotid,
                        vStepName,
                        vMagazineNo}, this.Perform_STG_QueryPPSPictureQtyOperationCompleted, userState);
        }
        
        private void OnPerform_STG_QueryPPSPictureQtyOperationCompleted(object arg) {
            if ((this.Perform_STG_QueryPPSPictureQtyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Perform_STG_QueryPPSPictureQtyCompleted(this, new Perform_STG_QueryPPSPictureQtyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public enum CommandType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        StoredProcedure,
        
        /// <remarks/>
        TableDirect,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public partial class OracleParameter : DbParameter {
        
        private int offsetField;
        
        private OracleDbType oracleDbTypeExField;
        
        private OracleDbType oracleDbTypeField;
        
        private int[] arrayBindSizeField;
        
        private OracleParameterStatus statusField;
        
        private OracleParameterStatus[] arrayBindStatusField;
        
        private OracleCollectionType collectionTypeField;
        
        private string udtTypeNameField;
        
        public OracleParameter() {
            this.offsetField = 0;
            this.statusField = OracleParameterStatus.Success;
            this.collectionTypeField = OracleCollectionType.None;
            this.udtTypeNameField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public OracleDbType OracleDbTypeEx {
            get {
                return this.oracleDbTypeExField;
            }
            set {
                this.oracleDbTypeExField = value;
            }
        }
        
        /// <remarks/>
        public OracleDbType OracleDbType {
            get {
                return this.oracleDbTypeField;
            }
            set {
                this.oracleDbTypeField = value;
            }
        }
        
        /// <remarks/>
        public int[] ArrayBindSize {
            get {
                return this.arrayBindSizeField;
            }
            set {
                this.arrayBindSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(OracleParameterStatus.Success)]
        public OracleParameterStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public OracleParameterStatus[] ArrayBindStatus {
            get {
                return this.arrayBindStatusField;
            }
            set {
                this.arrayBindStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(OracleCollectionType.None)]
        public OracleCollectionType CollectionType {
            get {
                return this.collectionTypeField;
            }
            set {
                this.collectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string UdtTypeName {
            get {
                return this.udtTypeNameField;
            }
            set {
                this.udtTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public enum OracleDbType {
        
        /// <remarks/>
        BFile,
        
        /// <remarks/>
        Blob,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        Clob,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Long,
        
        /// <remarks/>
        LongRaw,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        IntervalDS,
        
        /// <remarks/>
        IntervalYM,
        
        /// <remarks/>
        NClob,
        
        /// <remarks/>
        NChar,
        
        /// <remarks/>
        NVarchar2,
        
        /// <remarks/>
        Raw,
        
        /// <remarks/>
        RefCursor,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        TimeStamp,
        
        /// <remarks/>
        TimeStampLTZ,
        
        /// <remarks/>
        TimeStampTZ,
        
        /// <remarks/>
        Varchar2,
        
        /// <remarks/>
        XmlType,
        
        /// <remarks/>
        Array,
        
        /// <remarks/>
        Object,
        
        /// <remarks/>
        Ref,
        
        /// <remarks/>
        BinaryDouble,
        
        /// <remarks/>
        BinaryFloat,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public enum OracleParameterStatus {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        NullFetched,
        
        /// <remarks/>
        NullInsert,
        
        /// <remarks/>
        Truncation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public enum OracleCollectionType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        PLSQLAssociativeArray,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OracleParameter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public abstract partial class DbParameter : MarshalByRefObject {
        
        private DbType dbTypeField;
        
        private ParameterDirection directionField;
        
        private bool isNullableField;
        
        private string parameterNameField;
        
        private byte precisionField;
        
        private byte scaleField;
        
        private int sizeField;
        
        private string sourceColumnField;
        
        private bool sourceColumnNullMappingField;
        
        private DataRowVersion sourceVersionField;
        
        private object valueField;
        
        public DbParameter() {
            this.directionField = ParameterDirection.Input;
            this.parameterNameField = "";
            this.sourceColumnField = "";
            this.sourceColumnNullMappingField = false;
            this.sourceVersionField = DataRowVersion.Current;
        }
        
        /// <remarks/>
        public DbType DbType {
            get {
                return this.dbTypeField;
            }
            set {
                this.dbTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ParameterDirection.Input)]
        public ParameterDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNullable {
            get {
                return this.isNullableField;
            }
            set {
                this.isNullableField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ParameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
            }
        }
        
        /// <remarks/>
        public byte Precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        public byte Scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        public int Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SourceColumn {
            get {
                return this.sourceColumnField;
            }
            set {
                this.sourceColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SourceColumnNullMapping {
            get {
                return this.sourceColumnNullMappingField;
            }
            set {
                this.sourceColumnNullMappingField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(DataRowVersion.Current)]
        public DataRowVersion SourceVersion {
            get {
                return this.sourceVersionField;
            }
            set {
                this.sourceVersionField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public enum DbType {
        
        /// <remarks/>
        AnsiString,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Currency,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        Object,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Time,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        VarNumeric,
        
        /// <remarks/>
        AnsiStringFixedLength,
        
        /// <remarks/>
        StringFixedLength,
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        DateTime2,
        
        /// <remarks/>
        DateTimeOffset,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public enum ParameterDirection {
        
        /// <remarks/>
        Input,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        InputOutput,
        
        /// <remarks/>
        ReturnValue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public enum DataRowVersion {
        
        /// <remarks/>
        Original,
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        Proposed,
        
        /// <remarks/>
        Default,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DbParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OracleParameter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ASEKS.AutomationWebService.org/")]
    public abstract partial class MarshalByRefObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void LinkTestCompletedEventHandler(object sender, LinkTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetFAMachineTypeCompletedEventHandler(object sender, GetFAMachineTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFAMachineTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFAMachineTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PerForm_ASSY_QueryTableToXMLCompletedEventHandler(object sender, PerForm_ASSY_QueryTableToXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerForm_ASSY_QueryTableToXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerForm_ASSY_QueryTableToXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Perform_ASSY_QueryTableToStringCompletedEventHandler(object sender, Perform_ASSY_QueryTableToStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Perform_ASSY_QueryTableToStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Perform_ASSY_QueryTableToStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Perform_ASSY_QueryMESStepNameCompletedEventHandler(object sender, Perform_ASSY_QueryMESStepNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Perform_ASSY_QueryMESStepNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Perform_ASSY_QueryMESStepNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Perform_ASSY_QueryMESLotStateCompletedEventHandler(object sender, Perform_ASSY_QueryMESLotStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Perform_ASSY_QueryMESLotStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Perform_ASSY_QueryMESLotStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PerForm_FA_QueryTableToXMLCompletedEventHandler(object sender, PerForm_FA_QueryTableToXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerForm_FA_QueryTableToXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerForm_FA_QueryTableToXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Perform_FA_QueryTableToStringCompletedEventHandler(object sender, Perform_FA_QueryTableToStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Perform_FA_QueryTableToStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Perform_FA_QueryTableToStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Perform_FA_ExecuteNonQueryCompletedEventHandler(object sender, Perform_FA_ExecuteNonQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Perform_FA_ExecuteNonQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Perform_FA_ExecuteNonQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Perform_STG_ExecuteNonQueryCompletedEventHandler(object sender, Perform_STG_ExecuteNonQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Perform_STG_ExecuteNonQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Perform_STG_ExecuteNonQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void Perform_STG_QueryPPSPictureQtyCompletedEventHandler(object sender, Perform_STG_QueryPPSPictureQtyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Perform_STG_QueryPPSPictureQtyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Perform_STG_QueryPPSPictureQtyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591